### ISSUE TITLE
Deploy on Vercel

### ISSUE THREAD

**Issue by OlivierGuntenaar** [ixartz/Next-js-Boilerplate#138]
I've encountered an issue with the one-click deploy feature on Vercel. When I try to use it, I end up with an empty repository on my personal GitHub account. Below are the screenshots of the process:

> Attempting One-Click Deploy
<img width="410" alt="Screenshot 2023-07-07 at 23 07 50" src="https://github.com/ixartz/Next-js-Boilerplate/assets/62936143/88e5d052-673a-42e8-8901-8dadcba1ff0b">

> Resulting Empty Repository
<img width="776" alt="Screenshot 2023-07-07 at 23 02 21" src="https://github.com/ixartz/Next-js-Boilerplate/assets/62936143/d085ff62-da59-4de3-aed2-96af519211f2">

<img width="1163" alt="Screenshot 2023-07-07 at 23 03 07" src="https://github.com/ixartz/Next-js-Boilerplate/assets/62936143/1ee158c3-312f-4857-b4a2-df4f698794ac">

As a workaround, I tried copying the template to my git like so:

> Copying Template to Git

<img width="196" alt="Screenshot 2023-07-07 at 23 01 11" src="https://github.com/ixartz/Next-js-Boilerplate/assets/62936143/4cff1526-465b-41c7-972e-61f6dfb73f43">

However, this results in the framework preset being set to "Other":

> Framework Preset Set to Other

<img width="913" alt="Screenshot 2023-07-07 at 23 10 43" src="https://github.com/ixartz/Next-js-Boilerplate/assets/62936143/ab3a5ba6-e176-42dc-8bc5-61317700461c">

According to the [Vercel documentation](https://vercel.com/docs/concepts/deployments/configure-a-build#build-&-development-settings), it's possible to override the Framework Preset for a specific deployment by adding a framework to the vercel.json configuration.

Should we add this file to the repository to resolve the issue? I would appreciate any guidance or assistance on this matter.

**Comment by ixartz** [comment]
@OlivierGuntenaar, Thank you for reporting this issue. It's expected to automatically set the correct preset and not setting to "Other". This is not normal. Especially the project uses Next.js (built by vercel team)

Creating vercel.json can be a solution but it doesn't explain the root cause.

Not sure, but the error can be coming from this line: https://github.com/ixartz/Next-js-Boilerplate/blob/main/package.json#L27. It's because there is a post build step which cause the error?
