### ISSUE TITLE
Confusing naming between Schema and Validation.

### ISSUE THREAD

**Issue by luishdez** [ixartz/Next-js-Boilerplate#208]
Shouldn't be the Objects inside shcema folder called GuestbookSchema and the Objects inside validations GuestbookEditValidation...or GuestbookEditSchemaValidation ( maybe too long) instead of using the name Schema inside validation? 

meaning: 
schema: Schema of the database
validation: Schema for validation

**Comment by ixartz** [comment]
Totally agree with you. It's really confusion.

Indeed, Schema should refer to the database.
And Validation should used for validation instead of Schema.

So, we can rename guestbookTable to guestbookSchema
And, then in validation folder, rename GuestbookSchema to GuestbookValidation, EditGuestbookSchema to EditGuestbookValidation and DeleteGuestbookSchema to DeleteGuestbookValidation.

Do you think you can create the PR?

**Comment by luishdez** [comment]
Awesome. Sure. I'll do the PR tonight.

**Comment by ixartz** [comment]
Hi @luishdez, do you need some help?

**Comment by luishdez** [comment]
Hi sorry for the delay. Unexpected catastrophe at work 🤦🏻‍♀️. I think I'll be ok with the refactor. Working on it.

**Comment by ixartz** [comment]
Thank you for your help. Sure, no problem at all.

**Comment by ixartz** [comment]
Thank you for all your help especially in a busy time for you!
